name: haramainku_mam
description: HaramainKU Media Asset Manager — Mobile App for Field Crew & Editors
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # GraphQL
  graphql_flutter: ^5.1.2

  # Auth & Storage
  flutter_secure_storage: ^9.2.2

  # QR Scanner
  mobile_scanner: ^7.2.0

  # File handling
  file_picker: ^8.1.4
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  http: ^1.2.2
  workmanager: ^0.9.0

  # Push notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1

  google_sign_in: ^6.2.2

  # UI
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  # Utilities
  intl: ^0.19.0
  gal: ^2.3.2
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: "#141310"
  image: logo_app.png
  android_12:
    color: "#141310"
    image: logo_app.png
  ios: true
  android: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo_app.png"
  adaptive_icon_background: "#141310"
  adaptive_icon_foreground: "logo_app.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/welcome.png
    - logo_app.png
